server:
  port: 39999
  servlet:
    context-path: /sp
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
#配置日志
logging:
  level:
    '[org.springframework]': INFO
    '[com.gdxsoft]': INFO         
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  devtools:
    remote:
      secret: abcdefgh
    restart:
      additional-paths: 'src/main/java '
      enabled: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: emp-sqlprofiler
  
 
    
    
    
    